@startuml

actor users
users -> classes_id: 查看学生的班级
classes_id -> sub_id: 获取课程的id
sub_id -> students: 查看所有学生列表

alt 如果users是老师
	students -> grades
	grades -> tests
	tests --> users:每个学生的信息、及每个实验的成绩
else 如果users是students，或者未登录
    students --> users:每个学生的信息
end

@enduml